baseURL: 'http://example.org/'
languageCode: 'en-us'
title: Ari Safari
theme: PaperMod
paginate: 5
enableEmoji: true

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 40


params:
  homeInfoParams:
    Title: "Hi there 👋" 
    Content: Welcome to my blog, here you can find a lot of extraordinary journey
  socialIcons: # optional
    - name: "facebook"
      url: "www.google.com"
    - name: "instagram"
      url: "www.instagram.com"
    - name: "github"
      url: "www.github.com"

  profileMode:
    enabled: true
    title: "Hi there 👋" # optional default will be site title
    subtitle: "Welcome to my blog, here you can find a lot of extraordinary journey"
    imageUrl: "/images/logo.svg" # optional
    imageTitle: "<title of image as alt>" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
    - name: Archives
      url: "/archives/"
    - name: Github
      url: "https://github.com/"

  socialIcons: # optional
    - name: "instagram"
      url: "www.instagram.com"
    - name: "github"
      url: "www.github.com"


  assets:
    favicon: /images/logo.svg
  label:
    text: ""
    icon: /images/logo.svg
    iconHeight: 32
  cover:
    linkFullImages: true
    hiddenInList: true
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowShareButtons: true
  

  